### ISSUE TITLE
need update realm-cocoa (No such module 'RealmSwift')

### ISSUE THREAD

**Issue by saeedmozaffari** [RxSwiftCommunity/RxRealm#101]
i use from xcode 9, 
i can't build from RxRealm, because realm-cocoa version in **Cartfile.resolve** is older than latest version. now RxRealm use from `github "realm/realm-cocoa" "v3.0.0"` whiles latest verions is `github "realm/realm-cocoa" "v3.0.2"`. i was clone `RxRealm` and after than i manually update `realm-cocoa` to latest verions this problem was solved. 
but in main project that i used from `github "RxSwiftCommunity/RxRealm" "0.7.5"` and can't change it manaully!

Now how can i fix it?
please update `realm-cocoa` or give me another solution for this problem!

**Comment by icanzilb** [comment]
I don't really know anything about Carthage, but maybe you can try deleting the `Cartfile.resolved` and try installing dependencies again? Just a thought

**Comment by Blackening999** [comment]
Same  issue.  Only 0.7.5 is available at CocoaPods

**Comment by M0rtyMerr** [comment]
Just successfully install RxRealm via `Carthage` with `Xcode Version 11.4.1 (11E503a)`. Closing this, cause problem seems to be resolved. Feel free to reopen that issue in cause of any troubles!
