### ISSUE TITLE
Its possible to make an observable sequence out of a Result<Object> ?

### ISSUE THREAD

**Issue by ivangodfather** [RxSwiftCommunity/RxRealm#104]
Lets say i have a:
let results: Results<User> = realm.objects(User.self)
let obResults: Observable<Results<User>> = Observable.collection(from: results)

Now everytime that dataset changes i get a notification of an results object (an array), what i would like is to transform that obResults into Observable<User> and everytime a the original dataset changes i get just a next user value.

**Comment by icanzilb** [comment]
I'm not quite sure what you're trying to achieve. Could you explain in a different way (maybe with some pseudo code?)
