### ISSUE TITLE
Unable to fetch results on background thread

### ISSUE THREAD

**Issue by jessemx109** [RxSwiftCommunity/RxRealm#105]
Hello when I try and fetch results from realm on a background thread I get an exception inside of realm. To get around this I am having to switch to the main thread for all queries even if I don't need to

**Comment by freak4pc** [comment]
Are you sure the Realm itself is created on the thread from which you’re trying to fetch ?

**Comment by jessemx109** [comment]
Yes positive. The exception being thrown by Realm is 
"Can only add notification blocks from within runloops."

**Comment by jessemx109** [comment]
I do notice in the source code that the scheduler is passed in but never used in the Observable.array(from:) functions

**Comment by freak4pc** [comment]
In any way this is not a RxRealm Issue, but a Realm limitation. 

See here: https://github.com/RxSwiftCommunity/RxRealm/issues/11#issuecomment-228116773

**Comment by jessemx109** [comment]
I was able to work around this by subscribing instead of observing on a background scheduler following that post and another on the RxSwift repo
