### ISSUE TITLE
Observable.from(object: object) Not emitting event when sub object changes

### ISSUE THREAD

**Issue by jessemx109** [RxSwiftCommunity/RxRealm#107]
I am using Observable.from(object: object) to listen to changes on a realm object. If I make changes to the object I pass into the call they are reflected in the stream. If I make a change to a child object the stream doesn't not emit an event

The strange thing is in another piece of code I'm doing a similar thing but observing an array of items and the changes from their children trigger an onNext event

**Comment by rrozenv** [comment]
Having the exact same problem. Observable.changeSet(from: ) successfully relays changes if they are made to child realm objects, but Observable.from(object: ) only detects a change if the change is made directly to one if it's properties that is not another realm object.

**Comment by ghost** [comment]
Any workaround for this issue?

**Comment by pchmelar** [comment]
So far I'm using something like this:

```swift
extension Object {
    static func objectObservable<T: Object>(id: String) -> Observable<T> {
        let realm = try! Realm()
        let dbObjects = realm.objects(T.self).filter(NSPredicate(format: "id == %@", id))
            
        return Observable.collection(from: dbObjects).flatMap { (objects) -> Observable<T> in
            if let object = objects.first {
                return Observable.just(object)
            } else {
                return Observable.empty()
            }
        }
    }
}

let observable: Observable<User> = User.objectObservable(id: "0")
```

**Comment by M0rtyMerr** [comment]
Hey @rrozenv  @jessemx109 thank you for reporting that!
This is intended Realm behavior, please check this issue - https://github.com/realm/realm-cocoa/issues/5878
If you try to implement this behavior without RxRealm, you will see that it's similar.
```swift
class Test: Object {
    @objc dynamic var sub: SubTest?
}
class SubTest: Object {
    @objc dynamic var property = 1
}

let realm = try! Realm()
let test = Test()
let subTest = SubTest()
test.sub = subTest
try! realm.write {
    realm.add(test)
}
token = test.observe {
    print($0)
}
try! realm.write {
    subTest.property = 5 // notification from here won't be sent
}
```
RxRealm is a reactive extension to Realm. We can't modify Realm behavior :( 
I am afraid, this can't be fixed. Using provided workaround is totally fine.
