### ISSUE TITLE
WithoutNotifying: token - UI driven writes

### ISSUE THREAD

**Issue by hakkurishian** [RxSwiftCommunity/RxRealm#108]
I have a two-way binding like situation where I want to prevent the UI from updating a textfield every time the DB changes from its own source. 
My idea would be to use the commit without notifying API, but is this possible with RxRealm, can I acces it’s subscriptions token directly ?

**Comment by M0rtyMerr** [comment]
Hey @hakkurishian sadly you can't access `NotificationToken` directly.
RxRealm encapsulates `NotificationToken` inside and wraps it with RxSwift.Disposable. You may want to check RxRealm.swift:146 where this is implemented.

**Comment by M0rtyMerr** [comment]
close due to lack of activity, feel free to reopen
