### ISSUE TITLE
Support Xcode 10 and swift 4.2

### ISSUE THREAD

**Issue by SmolskyNeklo** [RxSwiftCommunity/RxRealm#112]

**Comment by adriantabirta** [comment]
Have the same problem

**Comment by freak4pc** [comment]
Seems to be an issue building Realm in Carthage: https://github.com/realm/realm-cocoa/issues/5928

Waiting on response there.

**Comment by freak4pc** [comment]
Can you share what exactly you tried? There is no detail in this. 
When using `carthage build --platform iOS` there is no issue.

As for a general Carthage installation, there is an open bug that was merged and waiting release there: https://github.com/Carthage/Carthage/pull/2561

On CocoaPod I also couldn't see an issue. Please share some more information :)

**Comment by cruisediary** [comment]
https://github.com/RxSwiftCommunity/RxRealm/tree/0.7.6 release

**Comment by adriantabirta** [comment]
freak4pc - thx, worked for me

**Comment by Blackening999** [comment]
Please update cocoa pods!

**Comment by freak4pc** [comment]
@carlosypunto @icanzilb You're the two only owners for this repo - could any of you push a new podspec? 

Also, if possible. could you add `community@rxswift.org` as an owner so everyone can upload a release later on? 

e.g.
`pod trunk add-owner RxRealm community@rxswift.org`

Thanks !
