### ISSUE TITLE
0.7.6 version is not available on cocoapods

### ISSUE THREAD

**Issue by mcousillas6** [RxSwiftCommunity/RxRealm#114]
Hey there! 

We were going to upgrade our app to target the latest version and we came into this issue.

Looks like `0.7.6` is not published on the registry.
The pod works fine installing it targeting the repo, so it's only missing to be pushed to cocoapods.

**Comment by freak4pc** [comment]
@icanzilb / @carlosypunto - You're the only two with the ability: 
![image](https://user-images.githubusercontent.com/605076/47564985-97e72b80-d92f-11e8-9d8a-b32bdbdd247d.png)

Would you also mind adding `community@rxswift.org` so others can help you ? 
e.g.
`pod trunk add-owner RxRealm community@rxswift.org`

**Comment by icanzilb** [comment]
done, @freak4pc can you verify you got access please?

**Comment by freak4pc** [comment]
Yup, thanks @icanzilb ! 

0.7.6 is out.
