### ISSUE TITLE
Help: about threading and autoreleasepool

### ISSUE THREAD

**Issue by DhbStudy** [RxSwiftCommunity/RxRealm#117]
In the Realm docs, they say:

" Wrapping all use of Realm APIs from background threads in explicit autorelease pools. "

But in the RxRealm, I haven't find that. Should I use RxRealm only in the main scheduler? or not?

**Comment by DhbStudy** [comment]
Here is the realm example:

```
DispatchQueue(label: "background").async {
    autoreleasepool {
        let realm = try! Realm()
        let theDog = realm.objects(Dog.self).filter("age == 1").first
        try! realm.write {
            theDog!.age = 3
        }
    }
}
```

**Comment by freak4pc** [comment]
Did you simple try a `subscribeOn` some background scheduler ?

**Comment by DhbStudy** [comment]
> Did you simple try a `subscribeOn` some background scheduler ?

Yes. Should I subscribeOn a scheduler like "RunLoopThreadScheduler" ?
