### ISSUE TITLE
Doesn't Sync with Real Platform 

### ISSUE THREAD

**Issue by Blackening999** [RxSwiftCommunity/RxRealm#119]
Hello, 

basically, the joyful journey into Realm ended up as terrible time loss.

https://docs.realm.io/sync/using-synced-realms/syncing-data#subscribing-to-data-reading-data

RxRealm doesn't work if you don't subscribe :\

I have 1 UserItem in my Realm

This code shows 0 users:
```
   let realm = try! Realm(configuration: SyncUser.current!.configuration())

    let users = realm.objects(UserItem.self)
    
    Observable.collection(from: users)
      .map {
        users in "\(users.count) user"
      }
      .subscribe(onNext: { text  in
        print(text)
      })
      .disposed(by: self.rx.disposeBag)
```

With this missing line, it shows correct "1 user"
```
    let _ = users.subscribe()
```

I originally thought RxSwift can handle returned SyncSubscription as the "subscribe" from Rx itself can be proxied properly and emit the token, on the store it as an Observable property (idk)

@icanzilb Do you want me to contribute on that matter?

**Comment by icanzilb** [comment]
I wouldn’t want to lose more of your time.

**Comment by Blackening999** [comment]
In case someone stuck on partial sync. I have found this workaround that works for me.
Hope it doesn't look like a crutch :) 

```swift
  func getViewer() -> Observable<UserItem> {
    guard let identity = SyncUser.current?.identity else { return .empty() }

    let realm = try! Realm(configuration: SyncUser.current!.configuration())
    let users = realm.objects(UserItem.self).filter("owner == %@", identity)

    let subscriptionToken = users.subscribe()

    return Observable.collection(from: users).flatMap { results -> Observable<UserItem> in
      return Observable<UserItem>.create { observer in
        if let user = results.first {
          observer.onNext(user)
        } else {
          print("NO  USER in RESULTS: \(results)")
        }
          
        return Disposables.create {
          subscriptionToken.unsubscribe()
        }
      }
    }
  }?.share()
    
    return result ?? .empty()  
      
  }
```
