### ISSUE TITLE
Need to upgrade to depend on RealmSwift 3.17 rather than still 3.14

### ISSUE THREAD

**Issue by g-enius** [RxSwiftCommunity/RxRealm#128]
Getting warnings for public func add<O: Object>(update: Bool = false,
                               onError: ((O?, Error) -> Void)? = nil) -> AnyObserver<O>

Warning:
'add(_:update:)' is deprecated: Pass .error, .modified or .all rather than a boolean. .error is equivalent to false and .all is equivalent to true.

**Comment by eharo2** [comment]
Any solution yet?

**Comment by vavlev** [comment]
Realm.UpdatePolicy.error

**Comment by Leonif** [comment]
realm.add(object, update: .all)

**Comment by fllaryora** [comment]
Thanks @Leonif , That solve my problem. Took me a while the meaning of your code be cause I have just come from goolge to this page.

**Comment by M0rtyMerr** [comment]
Closing this, cause issue was resolved!
