### ISSUE TITLE
Swift Package

### ISSUE THREAD

**Issue by natemann** [RxSwiftCommunity/RxRealm#129]
I see that at Package.swift has been added, but I am getting an error stating there is no Package.swift manifest for version 1.0.0. Is a new release needed to use RxRealm in as a Swift Package

**Comment by phongleq** [comment]
Looks like it might had been added to the pod workspace since the manifest file path is set to "Pod/Classes"

**Comment by freak4pc** [comment]
Can you try 1.0.1 ?

**Comment by phongleq** [comment]
> Can you try 1.0.1 ?

Thanks! That worked for me. Yesterday 1.0.0 was the minimum which was having issues.

**Comment by freak4pc** [comment]
Yup, there was a new Package.swift but no release.
