### ISSUE TITLE
Attempting to Install using Xcode 11 SPM fails cloning dependencies

### ISSUE THREAD

**Issue by Henriquedrdc** [RxSwiftCommunity/RxRealm#133]
When trying to install RxRealm using SPM it throws error cloning dependencies.

`Failed to clone 'src/external/pegtl'`

`Failed to clone 'Realm/ObjectStore'`

Is there anything we can do, or we just have to wait for those dependencies to support SPM ?

[error.txt](https://github.com/RxSwiftCommunity/RxRealm/files/3649156/error.txt)

**Comment by M0rtyMerr** [comment]
Just successfully install `RxRealm` via SPM with `Xcode Version 11.4.1 (11E503a)`. Closing this, cause problem seems to be resolved. Feel free to reopen that issue in cause of any troubles!
