### ISSUE TITLE
Update to RealmSwift 5?

### ISSUE THREAD

**Issue by arthur798** [RxSwiftCommunity/RxRealm#139]
Is there a planned release for RealmSwift 5? I am using this package however I can't update RxSwift to version 5 which removes UI webkit as I can't update RealmSwift 5 because of RxRealm not support version 5. is there anything planned at all?

**Comment by M0rtyMerr** [comment]
Hey @arthur798!
RealmSwift latest release version is `4.4.1`. Version 5 is still in beta. `RxRealm` currently supports RxSwift `5.*` and Realm `4.*`

**Comment by jenbitcoin** [comment]
Hi @MortyMerr Realm v5.0.0 is no longer beta. https://github.com/realm/realm-cocoa/releases/tag/v5.0.0  --- I hope RxRealm will be updated to use this version too.

**Comment by M0rtyMerr** [comment]
Thank you for update! I will take a look, API also requires update with freeze property 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by M0rtyMerr** [comment]
@jenbitcoin migrated to Realm 5 in latest release
