### ISSUE TITLE
 SPM - Target integrity: The package product 'Realm' requires minimum platform version 11.0 for the iOS platform, but this target supports 8.0

### ISSUE THREAD

**Issue by tristangrichard** [RxSwiftCommunity/RxRealm#144]
Xcode: 11.5
RxRealm: 3.0.0
Realm: 5.0.2
RxSwift: 5.1.1
iOS Deployment target: iOS 11.0

Getting errors:
 - The package product 'Realm' requires minimum platform version 11.0 for the iOS platform, but this target supports 8.0
- The package product 'RealmSwift' requires minimum platform version 11.0 for the iOS platform, but this target supports 8.0

**Comment by M0rtyMerr** [comment]
Thank you for reporting this! It was fixed in RxRealm 3.0.1

**Comment by tristangrichard** [comment]
Thanks!
