### ISSUE TITLE
Support for MongoDB Realm

### ISSUE THREAD

**Issue by hakkurishian** [RxSwiftCommunity/RxRealm#146]
It would be great to support [MongoDB Realm ](https://www.mongodb.com/realm)( RealmSwift >= 10.0).

**Comment by M0rtyMerr** [comment]
As I can see RealmSwift > 10.0 is still in beta

**Comment by hakkurishian** [comment]
It is. I'm testing RxRealm currently with it from my fork and so far it looks good. When it is out of beta I consider a PR.

**Comment by phatblat** [comment]
In the release notes for [`10.0.0-beta.5`](https://github.com/realm/realm-cocoa/releases/tag/v10.0.0-beta.5) it looks like they are adding support for Combine. Could RxRealm benefit from that by layering on top of the Combine APIs?

**Comment by hakkurishian** [comment]
Now the 2nd RC is there.

**Comment by freak4pc** [comment]
> Now the 2nd RC is there.

You said you have a fork. Why not submit a PR ?

**Comment by hakkurishian** [comment]
@freak4pc -my fork seems to work for the purpose of my app but I will need to run all tests to find potential bugs. However, except the podspec dependencies I did not change anything yet (since it seems to work).

**Comment by pierre-wehbe** [comment]
Any plans to support 10.0.0 soon?

**Comment by freak4pc** [comment]
If anyone wants to put up a full PR I'm happy to review and cut a release.

**Comment by phatblat** [comment]
There's a new [SwiftUI guide](https://docs.mongodb.com/realm/ios/swiftui/) up which demos use of the [`AsyncOpenPublisher`](https://realm.io/docs/swift/latest/api/Enums/RealmPublishers/AsyncOpenPublisher.html) (new in [10.1](https://github.com/realm/realm-cocoa/releases)). I may take a stab at a PR, but am still wrapping my head around Combine right now.

**Comment by hakkurishian** [comment]
Unfortunately my fork broke on the latest (10.0) release. I decided to use Combine + RealmPublishers and use simple wrappers to connect to Rx.

**Comment by rynecheow** [comment]
Do use v4.0.2 from Cocoapods @hakkurishian
