### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by axmav** [RxSwiftCommunity/RxRealm#150]
Xcode 12.0.1
Cocoapods: 1.9.3
RxRealm: 3.0.1

> Ld /Users/me/Library/Developer/Xcode/DerivedData/test-awuaaitkgjwnueaanzztsvjgomcs/Build/Products/Debug-iphonesimulator/RxRealm/RxRealm.framework/RxRealm normal (in target 'RxRealm' from project 'Pods')

Linking error:
> Undefined symbols for architecture x86_64:
>   "_OBJC_CLASS_$_RLMNotificationToken", referenced from:
>       objc-class-ref in RxRealm.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)

Can not build my project.. Have tried to remove cocoapods and install again.. Does not help..

**Comment by rubenbacanu** [comment]
+1

**Comment by jwomack440** [comment]
+1

**Comment by nvelichkin** [comment]
@Mazorati updating RealmSwift to 5.5.0 fix this issue for me

**Comment by liyu-wang** [comment]
+1

**Comment by Ar-Shak** [comment]
+1

**Comment by GaDaXaRa** [comment]
+1

**Comment by jessehao** [comment]
I solved this problem by updating macOS. 😂

macOS 10.15.4 -> macOS 10.15.7

**Comment by jessehao** [comment]
The solution works for me:

```shell
# delete CocoaPods Caches
rm -rf ~/Library/Caches/CocoaPods/Pods
# delete Pods/ folder of the project
rm -rf [YourProjectDir]/Pods
```

Then reinstall pods of your project.

**Comment by evansben87** [comment]
anyone resolve this issue?

**Comment by rynecheow** [comment]
@Mazorati Could you try again using the latest version on Cocoapods and let us know if the issue persists?
