### ISSUE TITLE
Opening Realm files of format version 20 is not supported by this version of Realm

### ISSUE THREAD

**Issue by tipshot** [RxSwiftCommunity/RxRealm#153]
describe：
I just started using swift and took over a swift project. After downloading an application from appStore and using it, then running it directly to the mobile phone through XCode, it will crash here. There has been a change between the online version and the current XCode version realm: podfile:'RealmSwift', '5.1.0' - > pod 'RealmSwift', '10.0.0', and then pod install.

Complete question：
Thread 1: Fatal error: 'try!' expression unexpectedly raised an error: Error Domain=io.realm Code=6 "Opening Realm files of format version 20 is not supported by this version of Realm" UserInfo={Error Code=6, NSFilePath=/var/mobile/Containers/Data/Application/DA7C97BB-1A81-40E9-A4F5-58AB0BC1D71E/Documents/default.realm, Underlying=Database has an unsupported version and cannot be upgraded

**Comment by rynecheow** [comment]
Do use v4.0.2 from Cocoapods @tipshot
