### ISSUE TITLE
Invalid `RxRealm.podspec` file: no implicit conversion of nil into String.

### ISSUE THREAD

**Issue by mstroshin** [RxSwiftCommunity/RxRealm#157]
Hello.
I tried to update RxRealm with cocoapods command: pod update
and get error: 

[!] Failed to load 'RxRealm' podspec: 
[!] Invalid `RxRealm.podspec` file: no implicit conversion of nil into String.

  from /var/folders/jy/_jg7v5ln4k37z0d73rz1k1ph0000gn/T/d20201216-3665-wntxxw/RxRealm.podspec:14
     s.authors = { "RxSwift Community" => "community@rxswift.org" }
     s.source = { :git => "https://github.com/RxSwiftCommunity/RxRealm.git", :tag => "v" + ENV["RELEASE_VERSION"] }
     s.swift_version = "5.1"
     
I guess the error in ENV["RELEASE_VERSION"]. I would send a PR, but I don't know how to fix it =)

**Comment by freak4pc** [comment]
Hey @rynecheow 
If you're using this for automation purposes you should move the template to a different file since some people link directly to the spec. 

Let me know if you need help

**Comment by mstroshin** [comment]
upd: this error only appears if the Podfile contains **git**
pod 'RxRealm', :git => 'https://github.com/RxSwiftCommunity/RxRealm.git'

After I removed it, everything was fine.

**Comment by freak4pc** [comment]
Yup, that makes sense - I imagine you linked directly to the pod spec in the repo which is why you bumped into this.
This is still an issue that we should solve so I tagged @rynecheow accordingly. Thanks for reporting!

**Comment by rynecheow** [comment]
@freak4pc Yeah will move it into a proper place as this is only for release automation. Thanks for reporting @mstroshin :)
