### ISSUE TITLE
RxRealm v4 should update iOS development target to v11

### ISSUE THREAD

**Issue by smartrejames** [RxSwiftCommunity/RxRealm#158]
Actually 3.0.1 had this fix #144

**Comment by 4omar9** [comment]
I am having this issue on xcode 12.3.

**Comment by rynecheow** [comment]
@omarmasripro @smartrejames Please try with v4.0.3

**Comment by rynecheow** [comment]
the issue should have been addressed.

**Comment by 4omar9** [comment]
@rynecheow Thank you it worked when I set the version to be **exactly** 4.0.3.

**Comment by smartrejames** [comment]
@rynecheow It worked! Thanks a lot
