### ISSUE TITLE
The linked framework 'RxRealm.framework' is missing one or more architectures required by this target: armv7.

### ISSUE THREAD

**Issue by hhl1809** [RxSwiftCommunity/RxRealm#161]
<img width="506" alt="Screen Shot 2021-02-25 at 12 11 01" src="https://user-images.githubusercontent.com/23712212/109106566-9f6aa980-7762-11eb-9e38-6685d3ed2fd8.png">
Hello I faced this issue when install RxRealm by Carthage. Any one can help ?

**Comment by JoeMatt** [comment]
What was your Carthage command?

**Comment by JoeMatt** [comment]
tested locally, and seems to build armv7 fine for me using cocoapods, swiftpm and carthage.

Please update and re-open if issues persists.
