### ISSUE TITLE
RealmSwift version 10.5.1 is no longer compatible with Xcode's latest version.

### ISSUE THREAD

**Issue by Sethmr** [RxSwiftCommunity/RxRealm#164]
RealmSwift 10.5.1 is the last version supported by RxRealm, but RealmSwift 10.5.2 has the fix for compatibility. I am forced to stay at Xcode version 12.4 until RxRealm can support this or I have to remove RxRealm from our library. 

Please let me know how long you think it will be before there is support. Thanks!

**Comment by icanzilb** [comment]
@Sethmr would you like to create a PR for the update?

**Comment by Sethmr** [comment]
We just transitioned to Combine. All the best for the RxSwift community. We were heading in that direction either way. Thank you for an awesome framework that helped out a ton!

**Comment by JoeMatt** [comment]
The current release is on 10.21.1
Closing as resolved.
