### ISSUE TITLE
Question Realm 4.4.1 RxSwift 6+

### ISSUE THREAD

**Issue by tristangrichard** [RxSwiftCommunity/RxRealm#166]
Hi you guys,

I have a lot of problems with the 5+ and 10+ versions of realm and do not feel like upgrading. Does anyone have a fork of RxRealm 2.0.0 that supports RxSwift 6+?

Cheers

**Comment by JoeMatt** [comment]
The current release is on RxSwift 6.5
Closing as resolved.
