### ISSUE TITLE
SortDescriptor Getting error on Xcode-13 beta 2 

### ISSUE THREAD

**Issue by aiaagentapp** [RxSwiftCommunity/RxRealm#169]
I am facing below SortDescriptor issues .

Reference to generic type 'SortDescriptor' requires arguments in <...>

Type of expression is ambiguous without more context

**Comment by JoeMatt** [comment]
Working for me in the latest Xcode 13.


If another package defines a class `SortDescriptor` you'll have to use namespace `RxRealm.SortDescriptor`

Closing, update if issues persist.
