### ISSUE TITLE
Unable to extend Reactive Realm in presence of RxRealm

### ISSUE THREAD

**Issue by arshiacont** [RxSwiftCommunity/RxRealm#174]
It is extremely useful to be able to refine custom reactive extensions for Realm on top of RxRealm. Defining such extension is currently not possible as the ad hoc `rx` extension of RxRealm has a base attribute with _private_ visibility, which prevents anyone using it in custom methods outside this pod.

Starting from RxSwift 6.1 version, it is – again – possible to use the somehow standard rx attribute of ReactiveCompatible protocol extension on a non-class type like Realm. ([ReactiveX/RxSwift#2285](https://github.com/ReactiveX/RxSwift/pull/2285))

This would also make this package "standard" in view of Reactive Extensions!

Pending PR #171 is currently addressing this issue which is pending Review. This issue is an attempt to create awareness and help bring that PR to the public.

**Comment by arshiacont** [comment]
@freak4pc any chance to move this further? Let me know if there’s another maintainer to ping! Happe new year ;)

**Comment by freak4pc** [comment]
Hey there, unfortunately I'm not sure there's an active maintainer for this project (I'm not maintaining it as well, just the org). 
Feel free to open a PR and I'll try to review it.

**Comment by arshiacont** [comment]
@freak4pc PR #171 Many thanks.
