### ISSUE TITLE
Last version of RxRealm not compiling

### ISSUE THREAD

**Issue by gorbat-o** [RxSwiftCommunity/RxRealm#175]
Hey guys,

I just did a pod update and then tried compiling
With the last Realm update, this repo doesn't compile anymore

![image](https://user-images.githubusercontent.com/7542553/149603234-bfe5c288-f424-4248-86d9-16c5846d0811.png)

![image](https://user-images.githubusercontent.com/7542553/149603247-2af0ce17-981f-4156-94a9-ef4ea5df4fa0.png)

I will rollback atm

**Comment by VipulDungranee** [comment]
@gorbat-o  I am having same issue , I can solve this by adding below in RxRealm.swift file


`extension NotificationEmitter {
    public func observe(on queue: DispatchQueue?, _ block: @escaping (RealmCollectionChange<Self>) -> Void) -> NotificationToken
        {
            NotificationToken()
        }
}`


by adding above extension its  solving problem but sometime app getting crash  
let me know anyone has proper solution on this

**Comment by arshiacont** [comment]
Update your RxRealm and it should be fine. Close the ticket if applicable.
