### ISSUE TITLE
🔝 New maintainer : was "This repo is looking for a maintainer! [Closed]"

### ISSUE THREAD

**Issue by freak4pc** [RxSwiftCommunity/RxRealm#176]
@JoeMatt and @rynecheow have been great past maintainers of this repo, but lately seems like they have less available time which is absolutely fine - but, it leaves this project in a bit of an unmaintained state.

I can't maintain this project unfortunately, especially since I'm not a Realm user. I just cut a new release with one of the PRs requested but I have no real way to confirm the code validity / functionality of this. 

If anyone (perhaps @PhilippeCuvillier ?) wants to take over this repo, please let me know! Thanks :)

**Comment by JoeMatt** [comment]
I don't believe I'm a maintainer on this, just RxReachability at the moment.

**Comment by jackhuynh-motorist** [comment]
Dear,

Can someone help to check because right now carthage can not build the RxRealm anymore, I guess because RxSwift updated from 6.2.0 to 6.5.0. Its raised this error:

`** ARCHIVE FAILED **


The following build commands failed:
	CompileSwift normal arm64
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler`

I still can fetch and build RxRealm success last week.

**Comment by arshiacont** [comment]
@jackhuynh-motorist I see that RxRealm 5.0.4 was just released by @lihao6485 (many thanks to him) and I suppose by looking at commits that it should clear things out on that side.
This being said, I don't see 5.0.4 iin the CocoaPods repository (which is still on 5.0.3): https://github.com/CocoaPods/Specs/tree/master/Specs/e/e/2/RxRealm 
@lihao6485 @rynecheow maybe additional action is necessary to push the podspec ?!

**Comment by arshiacont** [comment]
Sorry for the noise here: @rynecheow seems like your last _Release Action_ has failed on `deploy to cocoapods` due to some bad token issue: https://github.com/RxSwiftCommunity/RxRealm/runs/4862457996?check_suite_focus=true 
Looks like some one here should have received a verification email or similar! Therefore, the update is not showing on CocoaPods CDN.

**Comment by freak4pc** [comment]
Uploaded podspec:

```
 🎉  Congrats

 🚀  RxRealm (5.0.4) successfully published
 📅  January 19th, 22:20
 🌎  https://cocoapods.org/pods/RxRealm
 👍  Tell your friends!
```

**Comment by rynecheow** [comment]
@freak4pc Great if you could help to set the new Pods token in the repository's secret that would solve further Cocoapods release issues!

**Comment by freak4pc** [comment]
@rynecheow can you set it up? you should still have access to that CocoaPods account (rx-realm@rxswift.org)

**Comment by JoeMatt** [comment]
In other news, I linked up with @freak4pc . There was a misunderstanding of my past role in the project. I previously volunteered to help out with the project but it was not required at the time.

I am now officially the maintainer though. I also maintain RxReachability, which is a much smaller project. Also, I maintain Hero Transitions, libretro/VirtualJaguar, and am the founder of Provenance-EMU/Provenance.


Provenance (https://github.com/Provenance-Emu/Provenance) is a heavy user of RxRealm, so I have a vested interest in this project.

I do not have a lot of time to contribute, but I have a lot of experience doing code reviews and releases in SwiftPM and CocoaPods and that will be my main role. The community will be mostly responsible for code submissions.
