### ISSUE TITLE
Carthage build RxRealm fail

### ISSUE THREAD

**Issue by hhl1809** [RxSwiftCommunity/RxRealm#177]
Dear,

Can someone help to check because right now carthage can not build the RxRealm anymore, I guess because RxSwift updated from 6.2.0 to 6.5.0. Its raised this error:

`** ARCHIVE FAILED **

The following build commands failed:
CompileSwift normal arm64
CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler`

I still can fetch and build RxRealm success last week.

**Comment by rynecheow** [comment]
Hi, would you be able to contribute a fix for this? Would gladly review and merge.

**Comment by lihao6485** [comment]
Hi @hhl1809, you can update to v5.0.4, it should fix the problem.
