### ISSUE TITLE
Add CI to this repo

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxRealm#18]
heya folks - now accepting PRs to add CI for this repo, thanks! :)

**Comment by icanzilb** [comment]
I'll have a look at setting this up, I'm looking at travis anyway

**Comment by bontoJR** [comment]
I can help if necessary :)

**Comment by icanzilb** [comment]
no worries - I'll look how RxSwiftExt is setup, it's good for me to exercise this one more time ;) thanks!

**Comment by bontoJR** [comment]
_pfiu_ I just wrote because I was feeling sorry to have just you writing on this issue :trollface:

**Comment by icanzilb** [comment]
I already feel empowered by knowing someone keeps an eye on the issues nonetheless 👍

**Comment by bontoJR** [comment]
I am always watching 👽

**Comment by fpillet** [comment]
There's not much to do actually - add a `travis.yml` file in the repo, then you'll need to turn on the switch for `RxRealm` at https://travis-ci.org/profile/RxSwiftCommunity

**Comment by icanzilb** [comment]
if any of you has time on their hands - you're welcome to do it 👍

**Comment by fpillet** [comment]
I'm on it

**Comment by fpillet** [comment]
But but but ... for travis to work you need tests :)

**Comment by icanzilb** [comment]
Thanks @fpillet

**Comment by icanzilb** [comment]
maybe that wasn't such a great idea? now the build fails with the following message `Unknown File:0: Unexpected Failure:` and I honestly don't know how to fix that

**Comment by icanzilb** [comment]
This is better yes 
`** TEST SUCCEEDED: 16 passed, 0 failed, 0 errored, 16 total ** (538115 ms)`

And 7 minutes fast to run ... 👍

**Comment by icanzilb** [comment]
@fpillet - the first build passed, the second one failed again with: `Unknown File:0: Unexpected Failure:`

**Comment by icanzilb** [comment]
And the second time around the build again tool 17+ minutes - looks like really something different is happening on that first build

**Comment by fpillet** [comment]
I'm looking at the detailed logs, thing I figured out why. Another PR is on the way.

**Comment by fpillet** [comment]
So here is the issue: `RxRealmWriteSinks.swift` imports `RxCocoa` which I have specifically removed from tests to speed up the builds. I don't see any good reason for RxCocoa to be needed in the tests. If needed, then need to re-add `RxCocoa` as a dependency for the tests target in `Podfile`, otherwise need to remove the `import RxCocoa` directive from this file.

**Comment by icanzilb** [comment]
interesting ... I was planning on using `RxCocoa` but it seems like I didn't. I think we can skip testing with `bindTo(Observer)` if we already have test with `subscribe(Observer)`. Will remove the import and try again, thanks again @fpillet

**Comment by icanzilb** [comment]
@fpillet That didn't help ... https://github.com/RxSwiftCommunity/RxRealm/pull/20/commits/75c95406547861ec17fd6052681bd2bcc963ae63

The build is still failing:

```
Failures:
  0) -[RxRealmWriteSinks testRxAddObjectsInBackground] (RxRealm_Tests.xctest)
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
Unknown File:0: Unexpected Failure:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
** TEST FAILED: 17 passed, 0 failed, 1 errored, 18 total ** (536140 ms)
```

Where is the detailed log you mention? Maybe I can also have a look?

**Comment by fpillet** [comment]
It's always happening in `RxRealmWriteSinks textRxAddObjectsInBackground`. Would it be an issue with Realm having trouble accessing the database file in background on Travis? Could you use a Realm configuration that only uses an in-memory database?

See full log at:
https://s3.amazonaws.com/archive.travis-ci.org/jobs/135378662/log.txt

**Comment by icanzilb** [comment]
the cross-thread observing doesn't work with an in-memory realm (hey, maybe I discovered a bug I got to report?) ... I'll look into it some more

**Comment by icanzilb** [comment]
if anyone could provide more insight on the nature of the ci error that'd be great ...

**Comment by icanzilb** [comment]
Thanks again, the test was failing due to differences between OSX/Xcode and travis/Linux. I'll close this now
