### ISSUE TITLE
Add RxRealm.xcframework.zip to Github releases without dependencies

### ISSUE THREAD

**Issue by anuragajwani** [RxSwiftCommunity/RxRealm#182]
Thanks for adding the XCFramework for this project to the Github releases.

I have noticed that the XCFramework is quite large (> 800Mb). I assume that the binary contains its dependencies too. However I would like to reference an XCFramework in Github releases that does not contain any dependencies within as these are added separately to my project for other targets.

Basically I don't want to have two copies of Realm within my end app build.

Let me know if I can assist in any way to make this happen.

Anurag.

**Comment by freak4pc** [comment]
Hey, 
To my understanding xcframeworks don't have dependencies per-we, so the direct dependencies are usually bundled.

This doesn't necessarily mean you'll have two copies of Realm during linking. In my experience the compiler is smart enough to dynamically link just one instance as long as all versions match up.
