### ISSUE TITLE
iOS 17 incompatible

### ISSUE THREAD

**Issue by troovers** [RxSwiftCommunity/RxRealm#197]
The package isn't compatible with the upcoming version of iOS. It causes build issues because of the use of `Observable`, which is also being introduced in iOS 17.

![image](https://github.com/RxSwiftCommunity/RxRealm/assets/12065284/8d2f816f-8e0c-4111-b6f0-a24e28f61740)

![image](https://github.com/RxSwiftCommunity/RxRealm/assets/12065284/19518e28-e2c5-44ce-899d-507763829fdd)

I can confirm changing occurrences of `Observable` to `RxSwift.Observable` does fix the issues. That however is a temporary solution, which isn't doable on our CI machines.

**Comment by freak4pc** [comment]
Please see https://github.com/ReactiveX/RxSwift/issues/2532
