### ISSUE TITLE
Building with Xcode 15

### ISSUE THREAD

**Issue by fabianmuecke** [RxSwiftCommunity/RxRealm#199]
Builds using Xcode 15 currently fail due to [the infamous `Observation.Observable` vs `RxSwift.Observable` issue](https://github.com/apple/swift/issues/67815).

PR with the workaround incoming.

**Comment by arshiacont** [comment]
any news on this? This is blocking iOS 17 release for everyone @JoeMatt

**Comment by TheHiddenDuck** [comment]
Thanks for the PR, it solved the problem for me.
