### ISSUE TITLE
project not build in xcode 15.0

### ISSUE THREAD

**Issue by shahriar-ax** [RxSwiftCommunity/RxRealm#201]
showing error after updating pod
Cannot convert return expression of type 'Observable<Element>' to return type 'Observable<(Realm, Realm.Notification)>'

**Comment by johnmfriend** [comment]
I have the same issue. RxSwift has recently been updated to fix a similar issue I believe.

**Comment by asn111** [comment]
I am also unable to load my project and these are the issues it displays.
Any idea how to fix these?
Thanks 🙏 

<img width="1280" alt="Screenshot 2023-09-27 at 8 37 05 PM" src="https://github.com/RxSwiftCommunity/RxRealm/assets/8926549/501a22f4-db17-4bd4-b9cb-89944a1d6f33">

**Comment by shahriar-ax** [comment]
I fied the issue by using the PR code. You can also do this . Just go to
the PR code & copy past the code in your pod class.
Unlock the pod file first to do this.

Thanks

**Comment by brandy2015** [comment]
same  issue
