### ISSUE TITLE
Latest release (5.0.6) not compatible to latest RealmSwift versions because of Pod's version requirement

### ISSUE THREAD

**Issue by jaimeeee** [RxSwiftCommunity/RxRealm#207]
Latest release `5.0.6` has [the following version pinning](https://github.com/RxSwiftCommunity/RxRealm/blob/363c9a5595e3e99fcc435286078bc327ddb79bc8/RxRealm.podspec#L28C35-L28C35) on the `.podspec`:

`s.dependency "RealmSwift", "~> 10.40.1"`

Making it not compatible with `v10.41` or greater version (as of writing this, RealmSwift is already on `10.44.0`).

**Comment by jopache** [comment]
For what it's worth, I forked the repo, updated the pod spec and pointed my projects podfile towards the forked repo and it worked.  Not a great solution by any means, but the downgrade in this Repo was in a commit with comment "fix ci" so I won't bother PRing. 

in my projects podfile `pod 'RxRealm', :git => 'https://github.com/jopache/RxRealm.git'`
