### ISSUE TITLE
General question

### ISSUE THREAD

**Issue by plm75** [RxSwiftCommunity/RxRealm#23]
Hello, I hope it is OK to ask a question here.
I'm experimenting with RxRealm and in a ViewController, I’m trying to check if a RealmDB hasn’t been populated yet and if not, populate it with some seed values.

``` swift
    class CategoriesVC: UIViewController {
      let uiRealm = try! Realm()
      let disposeBag = DisposeBag()

      override func viewDidLoad() {
        super.viewDidLoad()
        seedCategories()
      }

      func seedCategories() {
        let stopSeeding = uiRealm.objects(Category)
          .asObservableArray()
          .map { $0.count > 4 }
          .filter { $0 == true }

        let categorySeeds = ["A", "B", "C", "D", "E"]
          .map { Category(name: $0) }
          .toObservable()

        categorySeeds
          .takeUntil(stopSeeding)
          .doOnNext({ a in
            print(("Create \(a.name)"))
          })
          .subscribe(Realm.rx_add())
          .addDisposableTo(disposeBag)
      }
    }

    class Category: Object {
      dynamic var name = ""

      convenience init(name: String) {
        self.init()
        self.name = name
      }
    }
```

Q1:  I'm having trouble understanding why this is not working ? New objects are inserted at each viewDidLoad. 

Q2: the documentation says “You can add newly created objects to a realm that you already have initialized” but there’s a compiler error if I replace `.subscribe(Realm.rx_add())` with `.subscribe(uiRealm.rx_add())` ?

**Comment by icanzilb** [comment]
hey did you find where your issue was

**Comment by plm75** [comment]
@icanzilb :  hello,
I got around this problem by using `combineLatest` instead:

``` swift
    let stopSeeding = uiRealm.objects(Category)
      .asObservableArray()
      .map { $0.count == 0}
      .filter { $0 == true }

    Observable
      .combineLatest(stopSeeding, Observable.just(["A", "B", "C", "D", "E"].map { Category(name: $0) })) { (flag, categories) -> [Category] in
        return flag == true ? categories : []
      }
      .doOnNext({ categories in print("create default categories: \(categories)") })
      .subscribe(uiRealm.rx_add())
      .addDisposableTo(disposeBag)
```

I think the problem with the initial approach was with `takeUntil` not emitting anything for some reason.

ps: enjoyed reading you rx blog BTW.  Hope there'll be more soon ;-)

**Comment by icanzilb** [comment]
yeah, I ran into health problems ... I hope I'll be able to pick that up again. good luck with your app
