### ISSUE TITLE
Update Documentation for Swift 3 API

### ISSUE THREAD

**Issue by mbalex99** [RxSwiftCommunity/RxRealm#32]
Update Documentation for Swift 3 API

The new API is all about a static extension method on `Observable` 

Can we update the docs? Let me know if you'd like me to help!

**Comment by icanzilb** [comment]
We certainly can, the current version is ofc more of a pre-release since it depends on RxSwift beta, which still might change... But if you have a bit of time on your hands go ahead and send a PR to fix the README 👍

**Comment by ast3150** [comment]
Hi guys, I filed pull request #35 with an updated README.

**Comment by icanzilb** [comment]
Thanks, merged
