### ISSUE TITLE
watchOS support in Podfile

### ISSUE THREAD

**Issue by mattjgalloway** [RxSwiftCommunity/RxRealm#37]
It'd be great to have watchOS support in for Cocoapods. I would do a pull request for it, but since you'll probably want to schedule it with a release, I thought it easiest just to ask here. But here's the line for you to copy pasta if you want!

```
s.watchos.deployment_target = '2.0'
```

(Thanks BTW - lovely little library this - helping me test out RxSwift and Realm in a new app!)

**Comment by icanzilb** [comment]
That's lovely Matt, thanks ... just solving my issue with CP on Sierra and afterwards will add watchos to the mix 👍

**Comment by icanzilb** [comment]
it's in
