### ISSUE TITLE
Wrong Commit To RxRealm repo

### ISSUE THREAD

**Issue by sendyhalim** [RxSwiftCommunity/RxRealm#40]
@icanzilb Hi I pushed a wrong commit to this repo https://github.com/RxSwiftCommunity/RxRealm/commit/15be918e21200910ba342ea0060763910f005f8c#diff-60bb710c5144ead8f8cb73a22de579ab

I was going to push it to my RxRealm forked repo 😓, is there anything that I can do? reverting it maybe (unless you're planning to upgrade to RxSwift 3.0)?

**Comment by icanzilb** [comment]
How is it wrong? And what should it be in its place?

**Comment by sendyhalim** [comment]
@icanzilb erm I mean, I should have opened a pull request instead of committed directly to master. I accidentally push the commit 15be918e21200910ba342ea0060763910f005f8c to this repo instead of the forked RxRealm repo 😅. I'm closing this since it looks like you're ok with the commit that I pushed. :beers:

**Comment by icanzilb** [comment]
that's okay - I guess best to do is to protect `master` 👍
