### ISSUE TITLE
Observing single object fails on device but works in simulator

### ISSUE THREAD

**Issue by juggernate** [RxSwiftCommunity/RxRealm#42]
If I run RxRealm_Example it works in simulator but I hit ```fatalError("At present you can't observe objects that don't have primary key.")``` when I try to run on device.

**Comment by stremsdoerfer** [comment]
Just posted a similar issue. Nice to see that I'm not the only one. I believe the issue is the line above though. On `type(of:object)`

**Comment by juggernate** [comment]
@JustaLab do you see a difference on simulator vs device?

**Comment by stremsdoerfer** [comment]
@juggernate yes, it works fine in the simulator.

**Comment by icanzilb** [comment]
confirmed, I'll look into it - very strange ...

**Comment by icanzilb** [comment]
the crash comes from the Swift standard library, `type(of:)` more specifically when running on a device - we'll have to consider a workaround maybe 🤔

**Comment by GabrielCartier** [comment]
Been running into this issue too.
I tried some workarounds without any success. 
The only option I have right now is to convert my single object calls to array calls and only get the first object. Not ideal but that does it for me right now.

**Comment by icanzilb** [comment]
I've been debugging this and it seems some kind of a Swift runtime error, right now I have no solution but to remove the single object observing from RxRealm ... I'll give it another try and if I don't find a reasonable solution I'll have to remove it

**Comment by insidegui** [comment]
Yeap, I am having the same issue. It crashes on device but works on the simulator.

**Comment by icanzilb** [comment]
fixed in latest release
