### ISSUE TITLE
Carthage error: Dependency "RxRealm" has no shared framework schemes

### ISSUE THREAD

**Issue by insidegui** [RxSwiftCommunity/RxRealm#44]
I am using Carthage version 0.18.1.

Cartfile snippet:
```
github "RxSwiftCommunity/RxRealm" ~> 1.0
```

When I run `carthage update RxRealm`, I get the following message:

```
Dependency "RxRealm" has no shared framework schemes
```

**Comment by dylan** [comment]
Same thing here, but more specifically:

```
*** Skipped building RxRealm due to the error:
Dependency "RxRealm" has no shared framework schemes for any of the platforms: iOS
```

When I run: `$ carthage update --platform ios`

**Comment by icanzilb** [comment]
anyone from the community wants to fix the Cartage support?

**Comment by dylan** [comment]
Sure, I can take a look at it.

**Comment by icanzilb** [comment]
fantastic @dylan, let me know if you need something!

**Comment by dylan** [comment]
It looks like legacy Swift 3.0 was picked in the compile options rather than the default "unspecified". Is there a particular reason for this? Otherwise just merge my PR and it now seems to work. https://github.com/RxSwiftCommunity/RxRealm/pull/45

**Comment by reloni** [comment]
@icanzilb 
I think problem here is in this [release](https://github.com/RxSwiftCommunity/RxRealm/releases/tag/1.0.5). It tagged with version 1.0.5, but actually latest version is 0.3.1
So if you write in cartfile `github "RxSwiftCommunity/RxRealm" ~> 1.0` carthage downloads this old vesion and can't build it. Now carthage works well with wersion 0.3.1 if it explicitly set in cartfile: `github "RxSwiftCommunity/RxRealm" == 0.3.1`

**Comment by dylan** [comment]
@reloni I cannot verify that this works. I get the same error in both cases.

**Comment by dylan** [comment]
Please check out https://github.com/RxSwiftCommunity/RxRealm/pull/46

**Comment by reloni** [comment]
@dylan it's strange, it works on my machine🤔
Can you provide full message, that carthage shows you?

**Comment by icanzilb** [comment]
@dylan I deleted the wrong tag as @reloni adviced, can you check if you're pulling the correct version now?
