### ISSUE TITLE
Please delete the 1.0.5 tag

### ISSUE THREAD

**Issue by bsrz** [RxSwiftCommunity/RxRealm#48]
This causes `Carthage` to download the wrong release.

**Comment by bsrz** [comment]
Or retag it as 0.1.5

**Comment by icanzilb** [comment]
done

**Comment by bsrz** [comment]
The tag is back:
![image](https://cloud.githubusercontent.com/assets/1077441/20989101/8606277e-bca1-11e6-8810-cf19c43e760f.png)

**Comment by bsrz** [comment]
Please remove the tag again.

**Comment by icanzilb** [comment]
omg, I re-pushed the tag when I committed here locally ... I deleted it now both locally and remotely. And I'm sure I will never tag a wrong version ever 😂

**Comment by bsrz** [comment]
haha thanks Marin!
Btw your Swift/Rx tutorials are awesome!
