### ISSUE TITLE
RLMException in case of binding Observable.arrayFrom() to tableView, RxRealm 0.4.0

### ISSUE THREAD

**Issue by ogrenich** [RxSwiftCommunity/RxRealm#55]
Hi, I found problem when using UITableView+Rx extensions or default UITableViewDataSource with Observable.arrayFrom() extension. If we are scrolling tableView, after write transaction to Realm app will crash with exception. Thanks in advance for recommendations and help.

_Exception_
*** Terminating app due to uncaught exception 'RLMException', reason: 'Object has been deleted or invalidated.'

**ViewModel**
```
import Foundation
import RxSwift
import RxCocoa
import RealmSwift
import RxRealm
import Moya
import Moya_ObjectMapper
import RxSwiftUtilities

struct BrandsViewModel {
    
    let bag = DisposeBag()
    let realm = try! Realm()
    let provider = Provider()
    let activityIndicator = ActivityIndicator()
    
    let results: Results<Brand>
    let changeset: Observable<(AnyRealmCollection<Brand>, RealmChangeset?)>
    let brands: Observable<[Brand]>
    let title: Observable<String>
    let state: Observable<State>
    
    
    init() {
        results = realm.objects(Brand.self)
        changeset = Observable.changesetFrom(results)
        brands = Observable.arrayFrom(results)
        
        title = Observable.from(results)
            .map {
                $0.count > 0 ? "Brands (\($0.count))" : "Brands"
            }
        
        state = Observable.combineLatest(brands, activityIndicator.asObservable()) {
            $0.isEmpty ? ($1 ? .loading : .empty) : .content
        }
        
    }
    
    func fetchData() {
        provider.request(.brands)
            .trackActivity(activityIndicator)
            .mapArray(Brand.self)
            .subscribe { event -> Void in
                switch event {
                case .next(let brands):
                    try! self.realm.write {
                        self.realm.delete(self.realm.objects(Brand.self))
                        self.realm.add(brands)
                    }
                case .error(let error):
                    print(error)
                default:
                    break
                }
            }
            .addDisposableTo(bag)
    }
    
}
```

**ViewController, UITableView+Rx -> RLMException**
```
import UIKit
import RxSwift
import RxCocoa

class BrandsViewController: UIViewController {

    @IBOutlet weak var activityIndicatorView: UIActivityIndicatorView!
    @IBOutlet weak var tableView: UITableView!
    
    let bag = DisposeBag()
    let viewModel = BrandsViewModel()
    
    
    override func viewDidLoad() {
        super.viewDidLoad()
        configureTableView()
        bindViewModel()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        viewModel.fetchData()
        
        if let indexPath = tableView.indexPathForSelectedRow {
            tableView.deselectRow(at: indexPath, animated: true)
        }
    }
    
}

extension BrandsViewController {
    
    func configureTableView() {
        tableView.register(BrandsTableViewCell.self)
        tableView.contentInset = UIEdgeInsets(top: 63.5, left: 0, bottom: 48.5, right: 0)
        tableView.sectionHeaderHeight = 32
        tableView.rowHeight = 44
    }
    
    func bindViewModel() {
        viewModel.title
            .bindTo(navigationItem.rx.title)
            .addDisposableTo(bag)
        
        viewModel.state
            .map {
                $0 == .loading
            }
            .bindTo(activityIndicatorView.rx.isAnimating)
            .addDisposableTo(bag)
        
        viewModel.state
            .map {
                $0 != .content
            }
            .bindTo(tableView.rx.isHidden)
            .addDisposableTo(bag)
        
        viewModel.brands
            .bindTo(tableView.rx.items) { (tableView, row, brand) in
                let cell: BrandsTableViewCell = tableView.dequeueReusableCell()
                return cell.configure(with: brand.name)
            }
            .addDisposableTo(bag)
     }
}
```

**ViewController, UITableViewDataSource –> RLMException**
```
var brands: [Brand] = []

...

func bindViewModel() {
        
        ...
        
        viewModel.brands
            .subscribe(onNext: { [unowned self] brands in
                self.brands = brands
                self.tableView.reloadData()
            })
            .addDisposableTo(bag)
}

extension BrandsViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return brands.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell: BrandsTableViewCell = tableView.dequeueReusableCell()
        return cell.configure(with: brands[indexPath.row].name)
    }

}
```

**ViewController, UITableViewDataSource and RealmChangeset –> RLMException**
```
func bindViewModel() {
        
        ...
        
        viewModel.changeset
            .subscribe(onNext: { [unowned self] brands in
                self.tableView.reloadData()
            })
            .addDisposableTo(bag)
}

extension BrandsViewController: UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return viewModel.results.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell: BrandsTableViewCell = tableView.dequeueReusableCell()
        return cell.configure(with: viewModel.results[indexPath.row].name)
    }

}
```

**Comment by gkuhlmann14** [comment]
What threads are your write transactions in `fetchData()`

Can you log/print a `Thread.isMain` right before the write? I think Moya moves to another thread for the backend call there so we could doublecheck that.

Also this occurs as you are scrolling and `fetchData` comes back or anytime `fetchData` is called (no matter where you are in the table)? Does it work the first time the call comes back (when realm is empty)?

**Comment by icanzilb** [comment]
I haven't tried using `RxRealm` with some built in table view bindings, but there is a separate pod that provides a custom binding specifically for Realm: https://github.com/RxSwiftCommunity/RxRealmDataSources

**Comment by ogrenich** [comment]
@gkuhlmann14 Thanks for your questions and suggestions.

1. Are we are on main thread right before the write transaction? – Yes, it is. It was first that I had tested. As I understand it is so because after completion request in background thread Moya bring us back to the main thread –  all events in a sequence which started on the main thread should be produced same thread by default. Thus, all actions in this case are going on the main thread. Please, correct me if I am wrong.

2. RLMExceptions occur only in case, when scrolling and `fetchData()` happen simultaneously. All works properly the first time (when Realm is empty) and if we are not scrolling tableView at the same time with the write transaction to Realm.

**Comment by ogrenich** [comment]
@icanzilb Hey Marin, thanks a lot for your suggestion. I like RxRealm and it's ease of use, but I expect that it should work also in simple cases without RxRealmDataSources and it seems very logical. For example [RxRealmDataSources](https://github.com/RxSwiftCommunity/RxRealmDataSources) uses Observable.changesetFrom() too and it works. What are you thinking about this?

**Comment by icanzilb** [comment]
@ogrenich of course it does work without RxRealmDataSources - if you need some inspiration check the demo app included in the repo, it demonstrates how to do updates, reads, etc.

**Comment by icanzilb** [comment]
oh now I understand what you want to do - you want to use `RxCocoa`'s `bindTo` operator to bind RxRealm collection directly to `tableView.rx.items`... I'm not sure this is possible at all to be honest.

**Comment by ogrenich** [comment]
@icanzilb Yeah! Now everything fell into place – we **must** use RxRealmDataSources for binding  RxRealm collections. Thanks a lot)

**Comment by igorleonovich** [comment]
By the way RxRealmDataSources seems like ignores MVVM concept and configures cells directly from a model passed to a controller.

**Comment by icanzilb** [comment]
RxRealmDataSources follows the same API design as RxDataSources and it's not bound to a certain app architecture
