### ISSUE TITLE
Observable.from broken ?

### ISSUE THREAD

**Issue by plm75** [RxSwiftCommunity/RxRealm#56]
I may have missed something, but it looks like `Observable.from` is broken: instead of calling the RxRealm method, it is RxSwift's "standard" `Observable.from` that is called.

To check this bug in action, just open the example app and look at  the section
```
        Observable.from(laps)
            .map {results in "laps: \(results.count)"}
            .subscribe { event in
                self.title = event.element
            }
            .addDisposableTo(bag)
```
if you insert an `onComplete` callback in the subscribe block, it will be called immediately.

Also, if you change the name of `Observable.from` to something else that doesn't
 conflict with RxSwift (e.g. `Observable.foo` then it works as expected.

**Comment by icanzilb** [comment]
This code is under test (here: https://github.com/RxSwiftCommunity/RxRealm/blob/master/Example/RxRealm_Tests/RxRealmResultsTests.swift#L40) 

What you are saying is that the observable completes immediately without being disposed?

**Comment by plm75** [comment]
What I'm saying is that instead of RxRealm's `from` method, calling `Observable.from` executes RxSwift's `from` method.  If you insert an `onCompleted` callback in the `subscribe` block, it will be called immediately after the initial `onNext` as it should with RxSwift's `from` but is not the expected behaviour with RxRealm's `from`

As I said, if you change the method's name in RxRealm's source code from `Observable.from` to something else like `Observable.foo` or `Observable.reactiveRealm_from` then it will work as expected.

A more trivial check would be to open the example app in Xcode, put the cursor on `Observable.from` (line 54) and look at the QuickHelp inspector that shows that the method is declared in RxSwift instead of RxRealm

**Comment by icanzilb** [comment]
Thanks for reporting this, it really seems the overload is broken... maybe due to recent change in RxSwift that improved working with optionals, not sure - I'll certainly have to look at fix this

**Comment by icanzilb** [comment]
weird though, it looks like it works just fine in the test suite, but not in the demo app. I'm totally confused 🤔

**Comment by icanzilb** [comment]
yes, figured this out - RxSwift 3.1 has broken all libs that override `Observable.from(_)` so I'll have to change the name of the method to keep it working. Thanks for reporting and noticing this 👍🏼

**Comment by icanzilb** [comment]
addressed in https://github.com/RxSwiftCommunity/RxRealm/pull/61
