### ISSUE TITLE
Error building RxRealm with Swift 3.

### ISSUE THREAD

**Issue by jonlambert** [RxSwiftCommunity/RxRealm#60]
I'm experiencing 29 Swift 3 related compiler errors when attempting to include RxRealm via Cocoapods. What's the correct way to install the library?

<img width="1075" alt="screen shot 2017-01-17 at 16 45 46" src="https://cloud.githubusercontent.com/assets/856225/22030079/75a67bec-dcd4-11e6-991f-b3e4f9182c7b.png">

**Comment by icanzilb** [comment]
The code on the screenshot looks like Swift 2.* Can you make sure you're using a recent version of RxRealm please.

**Comment by jonlambert** [comment]
Sorry, my mistake. I'm not specifying a version in my Podfile but a dependancy was! Thanks for your help.

**Comment by icanzilb** [comment]
can you share which was the dependency? I can have a look at leaving them a message or do a PR :)

**Comment by jonlambert** [comment]
It was an internal pod, consider it fixed! Thank you!
