### ISSUE TITLE
Do you have a plan for correspond to Object Notifications on Realm 2.4?

### ISSUE THREAD

**Issue by muukii** [RxSwiftCommunity/RxRealm#63]

**Comment by icanzilb** [comment]
@muukii  yes definitely, just a bit overwhelmed now with other work, but native object observable certainly coming in the next month 👍🏼

**Comment by muukii** [comment]
@icanzilb 
I got it. I am looking forward to it 😆

**Comment by ryanmeisters** [comment]
Started implementing this but then realized It wouldn't actually solve my problem. Here's a [gist](https://gist.github.com/ryanmeisters/b1bff4e16ed2578e43c28961777dce46) that may or may not be helpful to anyone needing this currently. It doesn't quite work--there's some issue with casting the observed value--but thought I'd post it anyway. 

@icanzilb is that gist along the lines of what you had in mind? Happy to help out if I can.

**Comment by TeunVR** [comment]
Maybe something like this?

```swift
import Foundation
import RealmSwift
import RxSwift
import RxRealm

public extension Observable where Element: Object {
    typealias PropertyChangeList = [PropertyChange]?
    
    public static func fromObject(object: Element) -> Observable<PropertyChangeList> {
        return Observable<PropertyChangeList>.create {
            observer in

            let token = object.addNotificationBlock{
                change in
                switch change {
                case .change(let properties):
                    observer.onNext(properties)
                case .deleted:
                    observer.onCompleted()
                case .error(let error):
                    observer.onError(error)
                }
            }
            
            return Disposables.create {
                token.stop()
            }
        }
    }
}

```

**Comment by icanzilb** [comment]
yes something along these lines should work, we'll just replace the existing object observation method with the new one. It'd be nice to also add a method on `Observable<PropertyChangeList>` to filter the changes by property name(s)

**Comment by icanzilb** [comment]
I think I will have time to grab the code above and add bunch of tests next week, stay tuned :)

**Comment by icanzilb** [comment]
This feature is added in https://github.com/RxSwiftCommunity/RxRealm/pull/71 . Will ship it with the next (imminent) release
