### ISSUE TITLE
How to observe the List if its Realm query prerequisite requirement has been changed?

### ISSUE THREAD

**Issue by wailaw** [RxSwiftCommunity/RxRealm#69]
Here is the structure of my database:

```swift
class Account: Object {
    dynamic var id = ""
    dynamic var username = ""

    let avatars = List<Avatar>()
    
    override static func primaryKey() -> String? {
        return "id"
    }
}

class Avatar: Object {
    dynamic var id = ""
    dynamic var name = ""
    
    let followingUsers = List<ChatTarget>()
    
    override static func primaryKey() -> String? {
        return "id"
    }
}

class ChatTarget: Object {
    dynamic var id = ""
    dynamic var username = ""
    
    let messages = List<MessageData>()
    
    override static func primaryKey() -> String? {
        return "id"
    }
}
```

Every user has an Account, and they can create many avatars in the Account. However, only one Avatar is active at the same time.
 
In my app, there is a tableView to show the current avatar's following users.
And this is simply achieved  by binding the search result to the tableView, i.e.

```swift
// currentAvatarID will be changed when users changing their current avatar 
Observable.from( realm.objects(Avatar.self).filter("id = '\(currentAvatarID)'").first?.followingUsers)
  .bindTo(tableView.rx.items) {tv, ip, followingUser in
    let cell = tv.dequeueReusableCell(withIdentifier: "Cell")!
    cell.textLabel?.text = followingUser.username
    return cell
  }
  .addDisposableTo(bag)
```

The problem is, as user can have multiple avatars in their account (**account.avatars**). And there will be only one avatar being active at the same time (found by the property **currentAvatarID**). 
I'll assign new value to the **currentAvatarID** after users change their avatar. 

What I want to achieve is the tableView will automatically updates the followingUsers of the current using avatar. Even after the user changes his avatar, the tableView can show the new followingUsers for the new currentAvatar.

However, the way I did now can only observe the followingUsers of the initial avatar...

How can I achieve this in RxSwift way? I'll be very appreciated if anyone can help. Many thanks.

**Comment by icanzilb** [comment]
Unfortunately `followingUsers` seems to be a constant, and won't trigger a change notification in its owning object. You can observe for changes on each of the `followingUsers` objects, that all users have, but depending on how many users there are this might be a bit of an overkill ... That's the only I can think of is
