### ISSUE TITLE
Consider support for addProgressNotification

### ISSUE THREAD

**Issue by DanielAsher** [RxSwiftCommunity/RxRealm#72]
Hi,

thanks for a great framework!

I was wondering if any thought had been given to adding support for progress notification via `addProgressNotification`

If you have any ideas please post them and I'll consider a [WIP] PR.

thanks,

Daniel

**Comment by icanzilb** [comment]
Hi Daniel, not just yet to be honest - I just merged the object notifications PR and hadn't had time to look into progress notifications ... are you using those in a project you're working on?

**Comment by DanielAsher** [comment]
I use playground scripts to manage ROS - and have found that awaiting synchronisation is required. The custom observables required are trivial, but I've not given thought, just yet, to production quality.

**Comment by icanzilb** [comment]
I'm on a bit of vacation, after wrapping up with the European part of the Realm tour ... once I'm back I'm gonna write you more about this. I got to try few things because I haven't used much these notifications myself before

**Comment by icanzilb** [comment]
Time has passed and I had to put out another release to fix more pressing issues, but this issue is one of the next things I'd like to look into. Have you meanwhile had some more insights into common use-cases for that API and what does make sense to build in RxRealm?

**Comment by DanielAsher** [comment]
@icanzilb I've not given it too much thought since implementing the simple functionality I required. Here is some sample code:
```
    private func realmSynchronizationProgress(for url: URL) -> Observable<(transfered: Int, transferable: Int)> {
        return Observable.create { observer in
            guard let session = SyncUser.current?.session(for: url)
                else {
                    observer.onError(RealmError.sessionSynchronization)
                    return Disposables.create()
            }
            let token = session.addProgressNotification(for: .download,
                                                        mode: .forCurrentlyOutstandingWork) { progress in
                observer.onNext((progress.transferrableBytes, progress.transferredBytes))
                if progress.isTransferComplete {
                    observer.onCompleted()  
                }
            }
            return Disposables.create {
                token?.stop()
            }
        }
    }

```
Parameterizing `for: .download, mode: .forCurrentlyOutstandingWork` is an obvious enhancement, but whether to depend on `RealmSwift` dataypes is an open question.

**Comment by DanielAsher** [comment]
Closed as stale.
