### ISSUE TITLE
TableView crash when Insert a value into a realm database. 

### ISSUE THREAD

**Issue by arunlj561** [RxSwiftCommunity/RxRealm#73]
Invalid update: invalid number of rows in section 0.  The number of rows contained in an existing section after the update (13) must be equal to the number of rows contained in that section before the update (13), plus or minus the number of rows inserted or deleted from that section (1 inserted, 0 deleted) and plus or minus the number of rows moved into or out of that section (0 moved in, 0 moved out).

My Code:- 
Datasource contains the realm results. 

         Observable.changeset(from: self.datasource)
            .subscribe(onNext: {[unowned self] results, changes in
                if let changes = changes {
                    self.contactsTableView.applyChangeset(changes)
                } else {
                    self.contactsTableView.reloadData()
                }
            })
            .addDisposableTo(self.disposeBag)

       extension UITableView {
         func applyChangeset(_ changes: RealmChangeset) {
        
        beginUpdates()
        deleteRows(at: changes.deleted.map { IndexPath(row: $0, section: 0) }, with: .automatic)
        insertRows(at: changes.inserted.map { IndexPath(row: $0, section: 0) }, with: .automatic)
        reloadRows(at: changes.updated.map { IndexPath(row: $0, section: 0) }, with: .automatic)
        endUpdates()
      }
    }

**Comment by icanzilb** [comment]
Hi, I don't see anything wrong with the code. This exact case is covered in the repo example app here: https://github.com/RxSwiftCommunity/RxRealm/blob/master/Example/RxRealm/ViewController.swift#L65

Does that work for you?

**Comment by arunlj561** [comment]
I have followed the same code, It crashes when Initially adding an object to the table, and when I update it.

**Comment by icanzilb** [comment]
If you send me a code that I can reproduce the crash I can have a look, otherwise as you see in the demo app that works.

**Comment by arunlj561** [comment]
I have created a sample project, you can check the sample code here. After the clone just click + on first screen and then again on second screen. It crashes. 
https://github.com/arunlj561/RxRealmStarter.git 
@icanzilb  have you checked, please let me know, Is something wrong written by me. 
Thanks in advance

**Comment by icanzilb** [comment]
You are refreshing your table view in your `viewWillAppear` method, that's why UIKit crashes when you try to apply the changes one more time to the table manually from your observable subscription.
