### ISSUE TITLE
rx.observe unmanaged object appears broken

### ISSUE THREAD

**Issue by grangej** [RxSwiftCommunity/RxRealm#80]
When I attempt to observe single properties on an unmanaged object now and then later create a realm I get back an error about duplicate properties in the schema for that object. This was working previously so i'm not sure what changed ? 

- Observing properties for an object that is already managed does not throw the error but this is not what I need.
- I have tried to remove the observe before creating the realm.
- the crash happens before I even attempt to add the object to the realm.

**Comment by icanzilb** [comment]
Hmm ... I never thought about observing unmanaged objects 🤔 Since RxRealm just wraps Realm's own notifications, I'll have to check what's the expected Realm notification behavior. Thanks for pointing this out

**Comment by freak4pc** [comment]
Interesting use case but I'm not 100% sure unmanaged objects get notifications? They are detached, eventually, and are _unmanaged_ by nature

**Comment by icanzilb** [comment]
The best way to approach this from my pov is to make a check if an object is unmanaged and throw if so. This shouldn't be how the API is to be used.

**Comment by grangej** [comment]
Can you please help to understand what a good pattern would be for an edit screen with throw-away changes in realm? 

Right now I found the safest approach is to create an unmanaged deep copy of an object and use that in the edit screen. 

This allows me to safely use this object as a scratch object and make changes and only save back to realm if the user decides to save, otherwise the we just discard the unmanned object when the user cancels. 

Right now because I can not watch properties of the unmanaged object for changes I have to write a lot of duplicate code to observe changes of those values.

**Comment by icanzilb** [comment]
Sorry for the late answer - why can't you observe for changes on the scratchpad object? You can with either plain KVO or RxSwift's kvo wrapper - Realm objects inherit from `NSObject` so they support KVO in full - that's also the recommended way to observe single properties on Realm objects in the docs.

**Comment by grangej** [comment]
Sorry for the late response to this: I am trying to do exactly what you say : use RxSwift KVO wrapper to watch for changes but when I do so on a unmanaged object and then later add that object to realm I get the crash. That is the problem. 

I do not see how this is expected behavior. We shouldn't have to worry about if the object is managed or not if we are using KVO should we?
