### ISSUE TITLE
Swift 4 support

### ISSUE THREAD

**Issue by RamwiseMatt** [RxSwiftCommunity/RxRealm#81]
It's early days still, of course, but are there any plans to rewrite the library to support Swift 4?

**Comment by freak4pc** [comment]
There's no reason to "Rewrite" it as its mainly very minor changes. 
I'm sure some work could be done to improve some pieces to conform to it but besides that, no real rewrite is needed IMO. 

It works fine in Xcode 9.0, tested :)

**Comment by RamwiseMatt** [comment]
Poor choice of wording on my part.

I'm attempting to use it in Xcode 9 beta 2, and its coming up with:

`/Pods/RxRealm/Pod/Classes/RxRealm.swift:238:14: 'map' produces 'Observable<R>', not the expected contextual result type '(Array<Self.E.ElementType>, RealmChangeset?)'`

My naive assumption was/is that this was a consequence of Swift 4 changes.

**Comment by freak4pc** [comment]
Are you using it in Swift 3 mode or Swift 4 mode ?

**Comment by RamwiseMatt** [comment]
Swift 4 (as defined in Build Settings -> Swift Language Version)

**Comment by freak4pc** [comment]
I don't think you would find many libraries that support Swift 4 out of the box right now. 
In this library's case it's even more complex since there are two heavy dependencies - 1. RealmSwift itself, 2. RxSwift itself 

I wouldn't expect seeing any progress on this until Xcode 9 reaches closer to a GM tbh

**Comment by icanzilb** [comment]
@RamwiseMatt in my pov it doesn't make sense to start updating RxRealm before there are Swift 4 versions of RxSwift and RealmSwift.

**Comment by icanzilb** [comment]
@RamwiseMatt it's been a while but I thought to ping you anyway - there has been a `swift4` branch for a while
