### ISSUE TITLE
What is the best way to deal with pagination?

### ISSUE THREAD

**Issue by ghost** [RxSwiftCommunity/RxRealm#82]
Hi, I'm just wondering, what is the best way to deal with pagination?
 
In this example we are getting all of the laps from Realm DB and then binding it to table

```swift
// create data source
let dataSource = RxTableViewRealmDataSource<Lap>(
  cellIdentifier: "Cell", cellType: PersonCell.self) {cell, ip, lap in
    cell.customLabel.text = "\(ip.row). \(lap.text)"
}

// RxRealm to get Observable<Results>
let realm = try! Realm()
let lapsList = realm.objects(Timer.self).first!.laps
let laps = Observable.changeset(from: lapsList)

// bind to table view
laps
  .bindTo(tableView.rx.realmChanges(dataSource))
  .addDisposableTo(bag)
```
What is the best way if I want to show only 20 first or last records and load older/newer records with pull to refresh or by scrolling to end begin/end of the table? Should I manually handle loading of paginatable data  "chunk" and then manually merge this data with table data source? Or maybe there is another better way to achive such behaviour?

**Comment by icanzilb** [comment]
hi @avitruk - it will help if you describe your use case in a bit more detail, I'm not sure what are you trying to achieve by not showing all results and then showing more rows in the table when the user reaches the bottom 🤔 Tell me why are you trying to do that?

**Comment by ghost** [comment]
Hi @icanzilb 
Well, for example, chat with message caching or something similar to this task? What if we have a lot of stored data, but we do not want to load all of them at the beginning? 

We can configure `NSFetchedResultsController` with` NSFetchRequest` and set fetchBatchSize to specific size. It allows to load data only when needed. So how can we achive this behaviour with Realm and Rx? Or are there reasons why it's not necessary?

**Comment by icanzilb** [comment]
@avitruk oh I see. You must be assuming that Realm works the same way as Core Data does. It doesn't. When you define `Results` in Realm you do not load any data in memory. There's no copying of data from the disk into memory - Realm only loads the objects you use at the moment - that's usually 5-6 table rows at any given time. As you scroll through your table or collection view Realm will fetch objects on the fly as you access them to populate the cells. 

There is a 6 part blog post series on realm.io if you are interested, this one specifically talks shortly about results in its first part: https://news.realm.io/news/realm-api-optimized-for-performance-and-low-memory-use/ (and you can find links to the other parts at the top of that page)

**Comment by ghost** [comment]
@icanzilb Oh, thank for the clarification and the link!

**Comment by icanzilb** [comment]
no problem at all 👍🏼
