### ISSUE TITLE
Argument labels '(object:)' do not match any variable overloads

### ISSUE THREAD

**Issue by 1cookspe** [RxSwiftCommunity/RxRealm#83]
![screen shot 2017-08-16 at 10 18 41 pm](https://user-images.githubusercontent.com/8737691/29393316-11e2f128-82d1-11e7-9131-a9570a1cda0f.png)

I receive an error of "Argument labels '(object:)' do not match any variable overloads" at line 508 of "RxRealm.swift", located at https://github.com/RxSwiftCommunity/RxRealm/blob/master/Pod/Classes/RxRealm.swift. It is triggered on the line of "return from(object: object)"

Any ideas on why this may be? I have RxRealm version 0.6.0 installed. 

Thanks for your help!

**Comment by freak4pc** [comment]
It should use the overload right below it. That's pretty interesting: 
https://github.com/RxSwiftCommunity/RxRealm/blob/master/Pod/Classes/RxRealm.swift#L520

**Comment by icanzilb** [comment]
@1cookspe are you using Carthage or CocoaPods?

**Comment by 1cookspe** [comment]
@icanzilb I am using CocoaPods

**Comment by icanzilb** [comment]
Strange, could you please try adding the object type like in the unit test: 
https://github.com/RxSwiftCommunity/RxRealm/blob/master/Example/RxRealm_Tests/RxRealmObjectTests.swift#L40

**Comment by 1cookspe** [comment]
Is this what you are referring to? I receive an error of "Use of undeclared type 'UniqueObject'"

![screen shot 2017-08-17 at 1 42 37 pm](https://user-images.githubusercontent.com/8737691/29425589-cdb5b702-8351-11e7-917b-32da12535f87.png)

**Comment by icanzilb** [comment]
No, do not edit the source code of RxRealm. I was suggesting you add the type of object you are observing to your own code. If you're not sure how to add a comment with the line of code which triggered the original error and what type of realm object is your observed object and I'll show you how to add the type.

**Comment by 1cookspe** [comment]
I'm not sure where this original error is triggered in my own code. Can you show me how to complete this? It would be much appreciated!

**Comment by icanzilb** [comment]
I'm not completely sure myself how to help you if you don't know where in your code you call the API which gives you the error. If you can provide more details I can try

**Comment by 1cookspe** [comment]
I install RxRealm by running the following code in my Podfile, correct?
`pod 'RxRealm'`

**Comment by icanzilb** [comment]
closing due to lack of details
