### ISSUE TITLE
Observable from optional (not working?)

### ISSUE THREAD

**Issue by Tarpsvo** [RxSwiftCommunity/RxRealm#84]
Hi.

I can not get my observable with binding to work.

My current usage is as follows:

Querying:
```
func rx_profile(_ userId: String) -> Observable<Profile?> {
    let realm = try! Realm()
    return Observable.from(optional: realm.object(ofType: Profile.self, forPrimaryKey: userId))
}
```

Using:
```
rx_profile()
      .map({ $0?.firstName })
      .observeOn(MainScheduler.asyncInstance)
      .bind(to: label.rx.text)
      .addDisposableTo(_bag)
```

Any consequent updates (`realm.write { realm.add(profile, update: true) }`) will not update the created binding.

What am I doing wrong? Or this not intended to work?

**Comment by icanzilb** [comment]
`Observable.from(optional:)` is not an RxRealm method - I'm not sure why does it not work.

**Comment by Tarpsvo** [comment]
Hi.

Reworking it to not use `Observable.from(optional:)` fixed the issue. I will emit an error instead if the object does not exist. Not a big fan of it, but it works.

**Comment by alekop** [comment]
This is still broken. I just wasted an hour tracking a bug down to this method, and rewrote my code to use `Observable.from(object:)` and emitting an error when not found.

**Comment by alekop** [comment]
The reason `Observable.from(optional)` doesn't track Realm changes is that it is not a RxRealm method! It comes from RxSwift, and doesn't know anything about Realm Results.
