### ISSUE TITLE
Do changeset observables work on background thread?

### ISSUE THREAD

**Issue by amccarri** [RxSwiftCommunity/RxRealm#88]
IOW does RxRealm handle managing run loops for background threads to be able to observe changes in the background rather than in main thread?

**Comment by icanzilb** [comment]
Not automatically. If you create a new thread based scheduler, install a run loop on it, and observe a collection on that thread - that'll work, but as said - that's not supported out of the box, you need to do your own setup (I was thinking about building something along those lines though)

Just in case you want to know more about notifications on bg threads: https://academy.realm.io/posts/realm-notifications-on-background-threads-with-swift/

**Comment by amccarri** [comment]
Thanks for the quick answer!  That article is actually what prompted me to ask this question.  I was thinking of doing something similar after reading that but wanted to check if RxRealm had already been there and done that.
