### ISSUE TITLE
RxRealm compatible with RxSwift 4

### ISSUE THREAD

**Issue by jdisho** [RxSwiftCommunity/RxRealm#89]
Currently RxRealm is compatible with RxSwift >= 3. When can it be compatible with RxSwift (4.0) ?

**Comment by freak4pc** [comment]
There's a branch: https://github.com/RxSwiftCommunity/RxRealm/tree/mt/swift4.0

**Comment by jdisho** [comment]
Thanks, but also the dependencies should be updated to: 
 -  s.dependency 'RealmSwift', '3.0.0'
 -  s.dependency 'RxSwift', '4.0.0'

I created a pull request for that 👍

**Comment by icanzilb** [comment]
Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by KarinaFernandez** [comment]
Do you have any idea of when is going to liber the new release? Thanks!

**Comment by icanzilb** [comment]
let's say within a week?

**Comment by KarinaFernandez** [comment]
I will be attentive to it. Thank you so much!

**Comment by icanzilb** [comment]
address in: https://github.com/RxSwiftCommunity/RxRealm/releases/tag/0.7.3
