### ISSUE TITLE
Support Carthage (PR Anyone?)

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxRealm#9]
Nobody has asked for Carthage support yet, but someone will. Probably just wait for a Carthage support PR

**Comment by RCacheaux** [comment]
@icanzilb I'm currently working on adding support, PR is almost ready. Should have it up in a couple of hours.

**Comment by icanzilb** [comment]
thank you Rene!

**Comment by RCacheaux** [comment]
#16 is ready for review, cheers 🍻

**Comment by icanzilb** [comment]
I'm sorry I meant "Rene" :)

**Comment by RCacheaux** [comment]
✌ no worries! I forgot to mention, can we tag the last commit with a version bump. It's so that carthage sees the xcode project when pulling down the latest tagged version from xcode.

**Comment by icanzilb** [comment]
@RCacheaux that okay? 0.1.6?

**Comment by RCacheaux** [comment]
@icanzilb perfect, thank you!
