### ISSUE TITLE
bring back ios8 support

### ISSUE THREAD

**Issue by icanzilb** [RxSwiftCommunity/RxRealm#95]

**Comment by Fouda** [comment]
hello I couldn't add RxRealm on swift3. I don't know which version I should specify
<img width="265" alt="screen shot 2017-10-27 at 12 29 09 pm" src="https://user-images.githubusercontent.com/12399604/32102015-d7d8c566-bb1a-11e7-9cb9-290fba0b543e.png">

This is what I get whenI tried to install the pod

<img width="574" alt="screen shot 2017-10-27 at 12 30 04 pm" src="https://user-images.githubusercontent.com/12399604/32102053-03f2545a-bb1b-11e7-9d78-7568985948c8.png">

**Comment by icanzilb** [comment]
The current version is  0.7.3 - it is swift 4/ and up to ios11, for swift 3 you can try 0.6.0. Also please open new issues when the existing issue is not related.
