### ISSUE TITLE
Adding unmanaged object to realm after using KVO causes exception

### ISSUE THREAD

**Issue by grangej** [RxSwiftCommunity/RxRealm#97]
As reference to previous ticket (closed) #80 

I am trying to do exactly what you say : use RxSwift KVO wrapper to watch for changes but when I do so on a unmanaged object and then later add that object to realm I get the crash. That is the problem.

I do not see how this is expected behavior. We shouldn't have to worry about if the object is managed or not if we are using KVO should we?

**Comment by icanzilb** [comment]
sorry, this repository is about RxRealm - if you get a crash with RxSwift, maybe open an issue there?
