### ISSUE TITLE
observeOn(): 'Only objects which are managed by a Realm support change notifications'

### ISSUE THREAD

**Issue by rs-georg** [RxSwiftCommunity/RxRealm#98]
When adding an object to Realm using a background queue the app crashes with the following exception:

`
*** Terminating app due to uncaught exception 'RLMException', reason: 'Only objects which are managed by a Realm support change notifications'
`

This is the class used to add the object:

```swift
class DataStore {

private let disposeBag = DisposeBag()
private let configuration = Realm.Configuration(deleteRealmIfMigrationNeeded: true)

func store(_ object: Object) {
  Observable
    .from(object: object)
    .observeOn(SerialDispatchQueueScheduler(qos: .background))
    .subscribe(Realm.rx.add(configuration: configuration, onError: { elements, error in
      if let _ = elements {
        print("Could not store elements")
      } else {
        print("Could not open Realm")
      }
    }))
  .disposed(by: disposeBag)
}

}
```

It's called from the main queue like this:

```swift
final class Cat: Object {
  @objc dynamic var id = UUID().uuidString
  @objc dynamic var name = ""

  override static func primaryKey() -> String? {
    return "id"
  }
}

let cat = Cat()
cat.name = "Emma"

let dataStore = DataStore()
dataStore.store(cat)
```

Versions used

```
github "realm/realm-cocoa" == 3.0.0
github "ReactiveX/RxSwift" == 4.0.0
github "RxSwiftCommunity/RxRealm" == 0.7.3
```

**Comment by freak4pc** [comment]
The error message seems rather indicative :) The Object you're trying to add isn't a Realm managed object. Also, this seems to me like a question to the main Realm repo and not specifically RxRealm related.

**Comment by rs-georg** [comment]
Yes, you're right. The object I add is not managed by Realm. That's why I call `Realm.rx.add(...` to add it to the Realm so it becomes a managed object. If I'm not completely mistaken that's how this is supposed to work. Or is there a different way to add an object to Realm?

Also, if I comment out the `.observeOn(...` line everything works fine.

**Comment by icanzilb** [comment]
@rs-georg what you're doing in your code is to create an observable sequence out of a single object's change notifications - this is not supported by Realm. You can read how to react to object change notifications here: https://github.com/RxSwiftCommunity/RxRealm#observing-a-single-object

What you're looking for is the API allowing you to add objects to realm: https://github.com/RxSwiftCommunity/RxRealm#rxadd

**Comment by rs-georg** [comment]
Thanks @icanzilb for your quick reply. I get it now.

I basically took the example from [#realmrxaddconfiguration](https://github.com/RxSwiftCommunity/RxRealm#realmrxaddconfiguration). Guess I can just put the single object into an array to make it work.

**Comment by icanzilb** [comment]
Yeah, give that a try and chime in if there’s still smth wrong
